engineer_advertises/urls.py
from django.urls import path
from . import views

app_name = 'engineer_advertises'

urlpatterns = [
    path('list/', views.EngineerAdvertisesList.as_view(), name='list'),
    path('mine/', views.MyEngineerAdvertisesList.as_view(), name='my_list'),
    path('<int:pk>/', views.EngineerAdvertiseDetail.as_view(), name='detail'),
    path('create/', views.CreateEngineerAd.as_view(), name='create'),
    path('statistic/<int:pk>/', views.Statistic.as_view(), name='statistic'),
    path('update/<int:pk>/', views.UpdateEngineerAdvertise.as_view(), name='update'),
    path('fake/', views.create_fake_ads, name='fake'),

]

sabtika/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('publics.urls', namespace='publics')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('emails/', include('emails.urls', namespace='emails')),
    path('advertises/', include('advertises.urls', namespace='advertises')),
    path('engineer/', include('engineer_advertises.urls', namespace='engineer_advertises')),
    path('withdrawal/', include('withdrawal.urls', namespace='withdrawal')),
    path('ca_invoice/', include('company_advertise_invoice.urls', namespace='ca_invoice')),
    path('en_invoice/', include('engineer_advertise_invoice.urls', namespace='en_invoice')),
    path('sms/', include('sms.urls', namespace='sms')),
    path('gateway/', include('gateway.urls', namespace='gateway')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
from django.urls import path
from . import views

app_name = 'sms'
urlpatterns = [
    path('resend/', views.resend_confirm_code, name='resend')
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('signup/', views.SignupUsersView.as_view(), name='signup'),
    path('login/', views.LoginUser, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.ProfileUsersView.as_view(), name='profile'),
    path('profile/confirm_phone_number', views.confirm_phone_number, name='confirm_phone_number'),
    path('bank_info/', views.UpdateBankInfo, name='bank_info'),
    path('forgot_password/', views.MyPasswordRestartView.as_view(), name='forgot_password'),
    path('password_reset_confirm/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_done/', views.MyPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset_complete/', views.MyPasswordResetCompleteView.as_view(),
             name='password_reset_complete'),


]

engineer_advertises/models.py
from django.db import models
from users.models import Users
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from .constants import CITIES, UNI_DEGREE, ADVERTISE_TYPE


# Create your models here.
class EngineerAdvertises(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    field = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=1000, null=True)
    degree = models.CharField(choices=UNI_DEGREE, max_length=30, blank=False, null=False)
    insurance_history = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(800)], null=True,
                                            blank=True)
    # location = models.CharField(choices=CITIES, max_length=30)
    # has_grade = models.BooleanField()
    price = models.DecimalField(decimal_places=0, max_digits=12)
    creation_date = models.DateTimeField(auto_now_add=True)
    is_approved = models.BooleanField(default=False)
    email_contact = models.BooleanField(default=False)
    mobile_contact = models.BooleanField(default=False)
    ladder_date = models.DateTimeField()
    urgent = models.BooleanField(default=False)
    advertise_type = models.CharField(choices=ADVERTISE_TYPE, max_length=30)

    def get_absolute_url(self):
        if self.engineeradvertiseinvoice.payment:
            return (reverse('engineer_advertises:my_list'))
        else:
            return (reverse('en_invoice:get', kwargs={'pk': self.engineeradvertiseinvoice.id, 'type': 'regular'}))

engineer_advertises/forms.py
from django import forms
from django.forms import ModelForm
from .models import EngineerAdvertises
from django.utils.translation import gettext as _
from .constants import UNI_DEGREE


class UpdateEngineerAdvertiseForm(ModelForm):
    has_insurance_history = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        super(UpdateEngineerAdvertiseForm, self).__init__(*args, **kwargs)

        self.fields['description'].widget.attrs = {'class': 'materialize-textarea'}
        self.fields['has_insurance_history'].required = False

        if kwargs['instance'].insurance_history == None:
            self.fields['insurance_history'].widget.attrs = {"min": "1", "max": "800", 'disabled': 'disabled'}
        else:
            self.fields['insurance_history'].widget.attrs = {"min": "1", "max": "800"}

        if kwargs['instance'].insurance_history != None:
            self.fields['has_insurance_history'].widget.attrs = {"checked": "checked"}

    class Meta:
        model = EngineerAdvertises
        fields = ['field', 'degree', 'insurance_history', 'price', 'description',
                  'price']
        widgets = {
            'description': forms.Textarea,
        }


class CreateEngineerAdvertiseForm(ModelForm):
    has_insurance_history = forms.BooleanField()
    accuracy = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        super(CreateEngineerAdvertiseForm, self).__init__(*args, **kwargs)

        self.fields['description'].widget.attrs = {'class': 'materialize-textarea'}
        self.fields['has_insurance_history'].required = False
        self.fields['insurance_history'].widget.attrs = {"min": "1", "max": "800", 'disabled': 'disabled'}

        # if kwargs['instance'].insurance_history == None:
        #     self.fields['insurance_history'].widget.attrs = {"min": "1", "max": "800", 'disabled': 'disabled'}
        # else:
        #     self.fields['insurance_history'].widget.attrs = {"min": "1", "max": "800"}
        #
        # if kwargs['instance'].insurance_history != None:
        #     self.fields['has_insurance_history'].widget.attrs = {"checked": "checked"}

    class Meta:
        model = EngineerAdvertises
        fields = ['field', 'degree', 'insurance_history', 'price', 'description',
                  'price', 'advertise_type']
        widgets = {
            'description': forms.Textarea,
        }

engineer_advertises/views.py
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from .models import EngineerAdvertises
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import CreateEngineerAdvertiseForm, UpdateEngineerAdvertiseForm
from publics.decorators import mobile_confirmed_required
from .decorators import owner_required
from django.shortcuts import render
from faker import Faker
from django.http import HttpResponse
from .constants import UNI_DEGREE, ADVERTISE_TYPE
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import redirect

# Create your views here.

class EngineerAdvertisesList(ListView):
    # page_template = 'advertises/list_page.html'
    template_name = 'engineer_advertises/list.html'
    paginate_by = 10

    # @method_decorator(login_required)
    # @method_decorator(email_confirmed_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):

        filters = {}
        if 'field' in self.request.GET:
            filters['field__icontains'] = self.request.GET['field']

        if 'degree' in self.request.GET:
            filters['degree'] = self.request.GET['degree']

        if 'insurance-from' in self.request.GET:
            filters['insurance_history__gte'] = self.request.GET['insurance-from']

        if 'insurance-to' in self.request.GET:
            filters['insurance_history__lte'] = self.request.GET['insurance-to']

        if 'price-from' in self.request.GET:
            filters['price__gte'] = self.request.GET['price-from']

        if 'price-to' in self.request.GET:
            filters['price__lte'] = self.request.GET['price-to']

        if 'advertise-type' in self.request.GET:
            filters['advertise_type'] = self.request.GET['advertise-type']

        if filters == {}:
            return EngineerAdvertises.objects.filter(engineeradvertiseinvoice__payment__exact=True).order_by('-ladder_date')
        else:
            return EngineerAdvertises.objects.filter(**filters, engineeradvertiseinvoice__payment__exact=True).order_by(
                '-ladder_date')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(EngineerAdvertisesList, self).get_context_data(object_list=None, **kwargs)
        context['degrees'] = UNI_DEGREE
        context['advertise_type'] = ADVERTISE_TYPE
        # context['cities'] = CITIES

        for obj in context['object_list']:
            obj.price = format(int(obj.price), ",d")

        return context

    def get(self, request, *args, **kwargs):

        return super(EngineerAdvertisesList, self).get(request, *args, **kwargs)


class MyEngineerAdvertisesList(ListView):
    # page_template = 'advertises/list_page.html'
    template_name = 'engineer_advertises/my-list.html'
    paginate_by = 10

    # @method_decorator(login_required)
    # @method_decorator(email_confirmed_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return EngineerAdvertises.objects.filter(user=self.request.user).order_by('-ladder_date')


class CreateEngineerAd(CreateView):
    form_class = CreateEngineerAdvertiseForm
    queryset = EngineerAdvertises.objects.all()
    template_name = 'engineer_advertises/create.html'

    @method_decorator(login_required)
    @method_decorator(mobile_confirmed_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        # if not request.user.first_name or not request.user.profile_picture:
        #     messages.add_message(self.request, messages.ERROR,
        #                          _('Your have to set your profile picture and name first! '))
        #     return redirect('users:profile', pk=request.user.id)

        return super(CreateEngineerAd, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        if form.cleaned_data['accuracy'] != True:
            messages.add_message(self.request, messages.ERROR, 'شما باید قوانین و مقررات را قبول کنید.')
            return redirect('advertises:create')
        form.instance.user = self.request.user

        now = timezone.now()
        form.instance.ladder_date = now
        return super(CreateEngineerAd, self).form_valid(form)


class Statistic(DetailView):
    model = EngineerAdvertises
    template_name = 'advertises/statistics.html'

    @method_decorator(login_required)
    @method_decorator(mobile_confirmed_required)
    @method_decorator(owner_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class EngineerAdvertiseDetail(DetailView):
    model = EngineerAdvertises
    template_name = 'engineer_advertises/detail.html'

    # @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EngineerAdvertiseDetail, self).get_context_data(**kwargs)
        context['object'].price = format(int(context['object'].price), ",d")
        return context


class UpdateEngineerAdvertise(UpdateView):
    form_class = UpdateEngineerAdvertiseForm
    queryset = EngineerAdvertises.objects.all()
    template_name = 'engineer_advertises/update.html'

    @method_decorator(login_required)
    @method_decorator(mobile_confirmed_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def create_fake_ads(request):
    user = request.user
    fake = Faker()
    for i in range(int(request.GET['num'])):
        field = 'مهندسی عمران'
        description = 'اول تو واتس آپ'
        degree = 2
        insurance_history = 30
        price = 25
        ad = EngineerAdvertises.objects.create(user=user, field=field, description=description, degree=degree,
                                               insurance_history=insurance_history,
                                               price=price)

    return HttpResponse('ok')


def ajax_list(request):
    # numbers_list = range(1, 1000)
    # page = request.GET.get('page', 1)
    # paginator = Paginator(numbers_list, 20)
    # try:
    #     numbers = paginator.page(page)
    # except PageNotAnInteger:
    #     numbers = paginator.page(1)
    # except EmptyPage:
    #     numbers = paginator.page(paginator.num_pages)
    return render(request, 'advertises/list_page.html')

engineer_advertises/templates/engineer_advertises/list.html
{% extends 'authenticated.html' %}
{% load static %}
{% block my_scripts %}

    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>

{% endblock %}
{% block content %}


    <main>

        <div class="container" id="suppo">
            <div class="row rtla second-menu" style="margin-bottom: -25px;">
                <div class="card updatecard2">
                    <ul class="tab">
                        <li class="tab col s6 center"><a class="lista " href="{% url 'advertises:list' %}">شرکت
                            ها</a>
                        </li>
                        <li class="tab col s6 center"><a class="lista active"
                                                         href="{% url 'engineer_advertises:list' %}">مهندسین</a>
                        </li>
                    </ul>
                </div>
            </div>

            <form method="get">
                <div class="row update rtla">
                    <div class="row card updatecard2 var-height eng-height">
                        <div class="col m12 l10 filter-box-list ">
                            <ul class="tab">
                                <li class="tab col m6 l3 s12 li-left-divider just-bottom-border-in-s"
                                    style="height: 45px;">
                                    <div class="input-field col s12" style="bottom: 17px;width: 95%">
                                        <div class="input-field col s12 left">

                                            <label for="field" class="">رشته</label>
                                            <input type="text" name="field" maxlength="100"
                                                   id="field" style="position: relative; bottom: 9px;">

                                        </div>
                                    </div>
                                </li>
                                <li class="tab col m6 l3 s12 li-left-divider not-display-in-m just-bottom-border-in-s"
                                    style="height: 45px;">
                                    <div class="input-field col s12" style="bottom: 17px;width: 95%">
                                        <select multiple name="degree">
                                            <option value="" disabled selected>مقطع</option>
                                            {% for degree in degrees %}
                                                {% if degree.0 != None %}

                                                    <option value="{{ degree.0 }}">{{ degree.1 }}</option>

                                                {% endif %}
                                            {% endfor %}

                                        </select>
                                    </div>
                                </li>
                                <li class="tab col m5 l3 display-in-m li-left-divider" style="height: 45px;">
                                    <div class="input-field col s12" style="bottom: 17px;width: 95%">
                                        <select multiple name="degree">
                                            <option value="" disabled selected>مقطع</option>
                                            {% for degree in degrees %}
                                                <option value="{{ degree.0 }}">{{ degree.1 }}</option>
                                            {% endfor %}

                                        </select>
                                    </div>
                                </li>
                                <li class="tab col m6 l4 s12 li-left-divider insurance-in-md  just-bottom-border-in-s"
                                    style="height: 45px">
                                    <div class="col s6" style="margin-top: 22px;">سابقه بیمه(ماه):</div>

                                    <div id="insurance_history" style="position: relative;
    bottom: 18px;">
                                        <div class="input-field col s3" style="margin-left: 10px;">
                                            <label class="number-input" for="insurance-from">از</label>
                                            <input id="insurance-from" name="insurance-from" type="number"
                                                   class="validate"
                                                   min="1" max="800">

                                        </div>
                                        <div class="input-field col s3">
                                            <label class="number-input" for="insurance-to">تا</label>
                                            <input id="insurance-to" name="insurance-to" type="number" class="validate"
                                                   min="1"
                                                   max="800">

                                        </div>
                                    </div>

                                </li>
                                <li class="tab col m5 l3 s12 li-left-divider just-bottom-border-in-s"
                                    style="height: 45px">
                                    <div class="col s6" style="margin-top: 24px;"> قیمت(تومان):</div>

                                    <div id="grade-from-to" style="position: relative;
    bottom: 18px;">
                                        <div class="input-field col s3" style="margin-left: 10px;">
                                            <label class="number-input" for="price-from">از</label>
                                            <input id="price-from" name="price-from" type="number" class="validate"
                                                   min="0">

                                        </div>
                                        <div class="input-field col s3">
                                            <label class="number-input" for="price-to">تا</label>
                                            <input id="price-to" name="price-to" type="number" class="validate" min="0"
                                            >
                                        </div>
                                    </div>

                                </li>


                            </ul>
                        </div>
                        <div class="col m12 l1 filter-box-list li-right-divider">
                            <select name="advertise-type">
                                <option value="" disabled selected>نوع آگهی</option>
                                {% for type in advertise_type %}
                                    {% if not type.0 %}
                                    {% else %}
                                        <option value="{{ type.0 }}">{{ type.1 }}</option>
                                    {% endif %}

                                {% endfor %}

                            </select>
                        </div>
                        <div class="col m12 l1">
                            <button class="waves-effect waves-light btn createbtn font  filter-button full-width-in-m-s"
                                    type="submit"
                                    name="button" value="search"> جست و
                                جو
                            </button>
                        </div>

                    </div>
                </div>
            </form>
            {% if not object_list %}
                <div class="row">
                    <div class="col s12">
                        <div class=" center">
                            <img class="empty responsive-img" src="{% static 'assets/supp/empty-result.png' %}" alt="">
                        </div>

                    </div>
                </div>
            {% endif %}


            <div class="row testin infinite-container">

                {% for ad in object_list %}
                    <div class="infinite-item">

                        <div class="col s12 m6 l3 card-list">
                            <div class="card small cara {% if ad.urgent == True %} urgent {% endif %}">

                                <div class="card-content">
                                    <div class="font2 otext center" style="color: #ad1457">
                                        <div class="row">
                                            <div class="col s1">&nbsp;</div>
                                            <div class="col s10 center">
                                                <img class="image-header-icon" src="{% if ad.advertise_type == '1' %}{% static 'assets/purchase.png' %}{% elif ad.advertise_type == '2' %}{% static 'assets/wanted.png' %}{% endif %}" alt="">
                                                <div class="ad-type">نوع آگهی: {{ ad.get_advertise_type_display }}</div>
                                            </div>
                                            <div class="col s1">&nbsp;</div>

                                        </div>
                                    </div>
                                <div class="divider"></div>
                                    <h6 class="font2 otext center">مدرک: {{ ad.field }} </h6>
                                    <h6 class="font2 otext center">مقطع: {{ ad.get_degree_display }} </h6>
                                    <h6 class="font2 otext center">سابقه بیمه:{% if ad.insurance_history %}
                                        {{ ad.insurance_history }} ماه
                                    {% else %}
                                        ندارد
                                    {% endif %}

                                        <h6 class="font2 otext center">قیمت: {{ ad.price }} تومان</h6>
                                        <div class="card-content" style="padding: unset;margin-top: 40px;">
                                            {% if ad.urgent == True %}

                                                <button style="width: 40%;"
                                                        onclick="window.location.href='{% url 'engineer_advertises:detail' pk=ad.id %}'"
                                                        class="waves-effect waves-light btn setbtn font btncan urgent-button"
                                                        type="button" name="button">فوری
                                                </button>
                                            {% else %}
                                                <button style="width: 40%;"
                                                        onclick="window.location.href='{% url 'engineer_advertises:detail' pk=ad.id %}'"
                                                        class="waves-effect waves-light btn setbtn font btncan"
                                                        type="button" name="button">بیشتر
                                                </button>
                                            {% endif %}

                                        </div>
                                    </h6>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>

        </div>

        <div class="container" style="text-align: center;">
            <img class="loading" style=" width: 75px;margin-top: 57px; display: none;"
                 src="{% static 'assets/gif/loading.gif' %}">
        </div>

        {% if page_obj.has_next %}
            <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
        {% endif %}


    </main>

{% endblock %}



{% block my_footer_script %}
    <script src="{% static 'js/infinit-scroll.js' %}"></script>

    <script>
        $(document).ready(function () {


            $("#grade-checkbox").change(function () {
                var status = $(this).prop('checked');
                if (status == true) {
                    {#                    $('#grade-from-to').show();#}
                    $('#grade-from').removeAttr('disabled');
                    $('#grade-to').removeAttr('disabled');

                    $('label.number-input').removeAttr('disabled');
                } else {
                    {#                    $('#grade-from-to').hide();#}
                    $('#grade-from').attr('disabled', 'disabled');
                    $('#grade-to').attr('disabled', 'disabled');
                    $('label.number-input').attr('disabled', 'disabled');

                }

            });

            $("#grade-checkbox-m").change(function () {
                var status = $(this).prop('checked');
                if (status == true) {
                    {#                    $('#grade-from-to').show();#}
                    $('#grade-from-m').removeAttr('disabled');
                    $('#grade-to-m').removeAttr('disabled');

                    $('label.number-input').removeAttr('disabled');
                } else {
                    {#                    $('#grade-from-to').hide();#}
                    $('#grade-from-m').attr('disabled', 'disabled');
                    $('#grade-to-m').attr('disabled', 'disabled');
                    $('label.number-input').attr('disabled', 'disabled');

                }

            });


        });
    </script>

    <script type="text/javascript">var arr = ["field"]</script>
    <script type="text/javascript" src="{% static 'js/persian.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/convert-to-persian-letter.js' %}"></script>


    <script src="{% static 'js/engineer-advertises/remove-empty-fields.js' %}"></script>

{% endblock %}

engineer_advertises/templates/engineer_advertises/list_page.html
{% extends 'authenticated.html' %}
{% load static %}
{% block my_scripts %}

    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    <script src="{% static 'js/nouislider.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/nouislider.css' %}">


{% endblock %}
{% block content %}
    <form action="" method="get">

        <select name="one" id="one1">
            <option value="a">aa</option>
            <option value="b">bb</option>
        </select>
        <input type="submit" value="asdasd" name="asd">
    </form>
{% endblock %}



{% block my_footer_script %}


{% endblock %}

engineer_advertises/templates/engineer_advertises/questions_edit.html
{% extends 'authenticated.html' %}
{% load static %}


{% block content %}
    <main>


        <div class="row update rtla">
            <div class="card updatecard">
                <table>
                    <thead>
                    <tr>
                        <th> سوال</th>
                        <th> عکس اول</th>
                        <th> عکس دوم</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for q in  question_list %}
                        <tr>
                            <td style="width: unset">سوال {{ q.question_number }}</td>

                            <td style="width: unset"><img src="{% get_media_prefix %}{{ q.first_pic }}" alt=""
                                                          class="imgupdate"></td>

                            <td style="width: unset"><img src="{% get_media_prefix %}{{ q.second_pic }}" alt=""
                                                          class="imgupdate"></td>

                            <td style="width: unset"><a href="{% url 'questions:update' pk=q.id %}"><img
                                    src="{% static 'assets/detail.png' %}" alt="" class="iconUpdate"></a></td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>


        </div>


    </main>

{% endblock %}

engineer_advertises/templates/engineer_advertises/statistics.html
{% extends 'authenticated.html' %}
{% load static %}


{% block content %}
  <main>


  <div class="row update rtla">
  <div class="card updatecard">
    <table>
    <thead>
      <tr>
          <th> سوال  </th>
          <th>   عکس اول  </th>
          <th>   تعداد انتخاب  </th>
          <th>   عکس دوم  </th>
          <th>   تعداد انتخاب  </th>
          <th>    </th>
      </tr>
    </thead>

    <tbody>
{% for q in  question_list%}
      <tr>
        <td style="width: unset">سوال {{ q.question_number }}</td>

        <td style="width: unset"><img src="{% get_media_prefix %}{{ q.first_pic }}" alt="" class="imgupdate"></td>
        <td style="width: unset">{{ q.count_of_first_pic }}</td>

        <td style="width: unset"><img src="{% get_media_prefix %}{{ q.second_pic }}" alt="" class="imgupdate"></td>
        <td style="width: unset">{{ q.count_of_second_pic }}</td>

        <td style="width: unset"><img src="{% static 'assets/detail.png' %}" alt="" class="iconUpdate"></td>
      </tr>
{% endfor %}

    </tbody>
  </table>
  </div>


  </div>


    </main>

{% endblock %}