advertises/urls.py
from django.urls import path
from . import views

app_name = 'advertises'

urlpatterns = [
    path('list/', views.AdvertisesList.as_view(), name='list'),
    path('mine/', views.MyAdvertisesList.as_view(), name='my_list'),
    path('<int:pk>/', views.AdvertiseDetail.as_view(), name='detail'),
    path('create/', views.CreateAd.as_view(), name='create'),
    path('statistic/<int:pk>/', views.Statistic.as_view(), name='statistic'),
    path('update/<int:pk>/', views.UpdateAdvertise.as_view(), name='update'),
    # path('<int:pk>/questions_edit/', views.QuestionsEdit.as_view(), name='questions_edit'),
    path('fake/', views.create_fake_ads, name='fake'),

]

emails/urls.py
from django.urls import re_path, path
from . import views

app_name = 'emails'

urlpatterns = [
    # url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
    path('resend_email/', views.resend_email, name='resend_email')
]

publics/urls.py
from django.urls import path
from . import views

app_name = 'publics'

urlpatterns = [
    path('', views.root, name='root'),
    path('about_us/', views.about_us, name='about_us'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('support/', views.support, name='support'),
]

sabtika/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('publics.urls', namespace='publics')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('emails/', include('emails.urls', namespace='emails')),
    path('advertises/', include('advertises.urls', namespace='advertises')),
    path('engineer/', include('engineer_advertises.urls', namespace='engineer_advertises')),
    path('withdrawal/', include('withdrawal.urls', namespace='withdrawal')),
    path('ca_invoice/', include('company_advertise_invoice.urls', namespace='ca_invoice')),
    path('en_invoice/', include('engineer_advertise_invoice.urls', namespace='en_invoice')),
    path('sms/', include('sms.urls', namespace='sms')),
    path('gateway/', include('gateway.urls', namespace='gateway')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
from django.urls import path
from . import views

app_name = 'sms'
urlpatterns = [
    path('resend/', views.resend_confirm_code, name='resend')
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('signup/', views.SignupUsersView.as_view(), name='signup'),
    path('login/', views.LoginUser, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.ProfileUsersView.as_view(), name='profile'),
    path('profile/confirm_phone_number', views.confirm_phone_number, name='confirm_phone_number'),
    path('bank_info/', views.UpdateBankInfo, name='bank_info'),
    path('forgot_password/', views.MyPasswordRestartView.as_view(), name='forgot_password'),
    path('password_reset_confirm/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_done/', views.MyPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset_complete/', views.MyPasswordResetCompleteView.as_view(),
             name='password_reset_complete'),


]

users/models.py
from django.db import models
from django.core.validators import EmailValidator, MinLengthValidator
from .validators import melli_code_validator
from django.utils.translation import ugettext_lazy as _
import re
from django.contrib.auth.base_user import AbstractBaseUser
from .managers import UserManager
from django.core.validators import ValidationError, RegexValidator
from PIL import Image
from io import BytesIO
from django.core.files import File
from publics.constants import profile_picture_size

import secrets


# Create your models here.


class Users(AbstractBaseUser):
    TESTER = 1
    TEST_OWNER = 2

    USER_ROLE_CHOICES = (
        (TESTER, _('Tester')),
        (TEST_OWNER, _('TestOwner'))
    )

    FEMALE, MALE = range(2)

    GENDER_CHOICE = (
        (FEMALE, _('Female')),
        (MALE, _('Male'))
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['phone_number']

    email = models.CharField(_('email'), db_index=True, max_length=50,
                             validators=[EmailValidator()], unique=True, null=False)
    # TODO phone number needed to be confirmed
    phone_number = models.CharField(_('phone number'), db_index=True, max_length=11,
                                    validators=[MinLengthValidator(11)], unique=True, null=True)
    is_phone_number_verified = models.BooleanField(default=False)
    phone_number_verification_code = models.CharField(max_length=128,
                                                      validators=[RegexValidator(regex='^[a-zA-Z0-9]{4,24}$')],
                                                      null=True)
    password = models.CharField(_('password'), validators=[RegexValidator(regex='^[a-zA-Z0-9]{4,24}$', message=_(
        'Password must be Alphanumeric , minimum 4 and maxium 24 charecter'),
                                                                          code='invalid_password')], max_length=128,
                                null=True,
                                blank=True)
    first_name = models.CharField(_('First Name'), max_length=50, null=True, blank=True)
    last_name = models.CharField(_('Last Name'), max_length=100, null=True, blank=True)
    card_number = models.CharField(_('Card Number'), max_length=16, null=True, blank=True,
                                   validators=[RegexValidator(regex='^[1-9]\d{15}$')])
    account_number = models.CharField(_('Account Number'), max_length=22, null=True, blank=True,
                                      validators=[RegexValidator(regex='^\d*$')])
    shaba_number = models.CharField(_('Shaba Number'), max_length=26, validators=[RegexValidator(regex='^IR[\d]{24}$')],
                                    null=True, blank=True)
    # TODO melli code can change just one time after confirmation
    melli_code = models.CharField(validators=[melli_code_validator], null=True, blank=True, max_length=10)
    profile_picture = models.ImageField(null=True, blank=True, upload_to='user_data/profile_picture/')
    birth_date = models.DateField(null=True, blank=True)
    role = models.PositiveSmallIntegerField(choices=USER_ROLE_CHOICES, default=TESTER)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICE, null=True, blank=True)
    instagram = models.CharField(max_length=100, null=True,blank=True)
    telegram = models.CharField(max_length=100, null=True,blank=True)
    is_pro = models.BooleanField(default=False)
    is_banned = models.BooleanField(_('is banned'), default=False)

    # For django's built-in superusers
    is_admin = models.BooleanField(_('admin status'), default=False)
    # Is active field tells if user is an active user or is a previous user of the system.
    # If user is inactive he/she only can view related data.
    is_active = models.BooleanField(_('active'), default=True)

    # Is verified field tells if user has verified his/her phone number or not.
    is_verified = models.BooleanField(_('verified'), default=False)

    # @property
    # def user_node(self):
    #     if self.is_authenticated:
    #         return self.insure_integrity_of_user_node()
    #     return None
    REQUIRED_FIELDS = []

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    # def save(self, *args, **kwargs):
    #     self.set_password(self.password)
    #     return super(Users, self).save(*args, **kwargs)

    def create(self, validated_data):
        """
        Create and return a new `User` instance, given the validated data.
        """
        if not validated_data['email']:
            raise ValueError('Email is required.')
        if validated_data['role'] not in (1, 2):
            raise ValueError('Role not defined.')
        role = 1
        is_active = False

        user = Users(email=validated_data['email'], is_active=is_active, role=role)
        user.set_password(validated_data['password'])
        user.save()

        return user

    # TODO what?
    def update(self, instance, validated_data):
        """
        Update and return an existing `Snippet` instance, given the validated data.
        """
        instance.melli_code = validated_data.get('title', instance.melli_code)
        instance.profile_picture = validated_data.get('code', instance.profile_picture)
        instance.birthday_date = validated_data.get('linenos', instance.birthday_date)
        instance.role = validated_data.get('language', instance.role)
        instance.mobile_number_varified = validated_data.get('style', instance.mobile_number_varified)
        instance.gender = validated_data.get('style', instance.gender)

        instance.save()
        return instance

    @staticmethod
    def is_phone_number_correct(phone_number):
        phone_number = Users.correct_phone_number_structure(phone_number)
        pattern = re.compile("^09\d{9}$")
        return bool(pattern.match(phone_number))

    @staticmethod
    def correct_phone_number_structure(phone_number):
        pattern_1 = re.compile("^9\d{9}$")
        pattern_2 = re.compile("^09\d{9}$")
        pattern_3 = re.compile("^00989\d{9}$")
        pattern_4 = re.compile("^\+989\d{9}$")

        if bool(pattern_1.match(phone_number)):
            return "0" + phone_number
        if bool(pattern_2.match(phone_number)):
            return phone_number
        if bool(pattern_3.match(phone_number)):
            return "0" + phone_number[4:]
        if bool(pattern_4.match(phone_number)):
            return "0" + phone_number[3:]

        # just for readability
        raise ValueError('phone number is not valid.')

    @staticmethod
    def check_if_phone_number_correct(phone_number):
        # this method use for cases we dont want to check and catch exception directly. for example in views
        if not Users.is_phone_number_correct(phone_number):
            raise ValidationError({'detail': _('your phone number is not correct.enter a correct one.')})

    @staticmethod
    def get_user_by_phone_number(phone_number):
        return Users.objects.filter(phone_number=phone_number).first()

    def get_absolute_url(self):
        return u'/users/login/?register=True'

    @staticmethod
    def create_one_time_pin(digit_count=6):
        start = int("1" + ("0" * (digit_count - 1)))
        stop = int("9" * digit_count)
        return secrets.choice(range(start, stop))

    def check_confirm_code(self, code):
        if self.phone_number_verification_code == code:
            return True
        return False

    def handle_sent_confirmation_code(self, code):
        if self.check_confirm_code(code):
            self.phone_number_verification_code = None
            self.is_phone_number_verified = True
            self.save()
            return
        else:
            raise ValidationError({'detail': 'کد ارسال شده اشتباه است'})

    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #     db_wt = Users.objects.filter(pk=self.pk).first()
    #     if db_wt != None:
    #         if db_wt.phone_number != self.phone_number:
    #             update_fields = ['phone_number']
    #         return super(Users, self).save(force_insert=False, force_update=False, using=None,
    #                                        update_fields=update_fields)
    #     return super(Users, self).save(force_insert=False, force_update=False, using=None,
    #                                    update_fields=None)

users/forms.py
from django.forms import ModelForm
from .models import Users
from django import forms
from django.utils.translation import gettext as _
from PIL import Image
from io import BytesIO
from django.core.files import File
from publics.constants import profile_picture_size, max_profile_size, acceptable_image_type


class SignUpUsersForm(ModelForm):
    privacy = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        super(SignUpUsersForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs = {'class': 'validate'}
        self.fields['password'].widget.attrs = {'class': 'validate', 'pattern': '^[a-zA-Z0-9]{4,24}$'}
        self.fields['phone_number'].widget.attrs = {'class': 'validate', 'pattern': '^09\d{9}$',
                                                    'title': 'شماره موبایل 11 رقم بوده و با 09 شروع میشود.'}

    def is_valid(self):
        for field in self.fields:
            if field in self.errors:
                self.fields[field].widget.attrs['class'] += ' invalid'

                for index, error in enumerate(self.errors[field]):
                    self.errors[field][index] = _(error)

        return super(SignUpUsersForm, self).is_valid()

    class Meta:
        model = Users
        fields = ['email', 'password', 'phone_number']
        widgets = {
            'password': forms.PasswordInput(),
            'email': forms.EmailInput(),
        }

    # set_password is for hashing password before call save in model . if set True. if false , nothing happend. also set_password value not passed to super
    def save(self, commit=True, set_password=True):
        if set_password:
            self.instance.set_password(self.instance.password)
        user = super(SignUpUsersForm, self).save(commit=commit)
        return user


class LoginUsersForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(max_length=24, widget=forms.PasswordInput)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['first_name', 'profile_picture', 'phone_number', 'instagram', 'telegram']

    def clean(self):
        if self.cleaned_data:
            if 'profile_picture' in self.cleaned_data:
                if self.cleaned_data['profile_picture'] != None:
                    # if first error appear, django remove first pic from clean data
                    size_error, postfix_error = False, False

                    if self.cleaned_data['profile_picture'].size > max_profile_size:
                        size_error = True
                    if 'content_type' in dir(self.cleaned_data['profile_picture']):
                        if self.cleaned_data['profile_picture'].content_type not in acceptable_image_type:
                            postfix_error = True

                    if postfix_error:
                        self.add_error('profile_picture', _("the only acceptable files format are jpeg and png"))
                    if size_error:
                        self.add_error('profile_picture', _("profile picture have to be less than 1 megabyte"))

                    if self.errors != {}:
                        return super(ProfileForm, self).clean()

                    if 'content_type' in dir(self.cleaned_data['profile_picture']):
                        size = profile_picture_size
                        profile_picture = self.cleaned_data['profile_picture']
                        im = Image.open(profile_picture)
                        im.thumbnail(size, Image.ANTIALIAS)
                        out = BytesIO()
                        im.save(out, format=profile_picture.image.format)
                        self.cleaned_data['profile_picture'] = File(out, name=profile_picture.name)
        return super(ProfileForm, self).clean()



        # def clean_profile_picture(self):
        #     size = (512, 512)
        #     profile_picture = self
        #     im = Image.open(profile_picture)
        #     im.thumbnail(size, Image.ANTIALIAS)
        #     out = BytesIO()
        #     im.save(out, format='jpeg', quality=99)


class UpdateBankForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['account_number', 'shaba_number', 'card_number']

users/templates/users/confirm_phone_number.html
{% extends 'authenticated.html' %}
{% load static %}

{% block title %}ثبتیکا|تایید شماره تلفن{% endblock %}
{% block content %}
    <main>


        <div class="row login1">
            <div class="col s12">
                <div class="card-panel white">

                    <h5 class="center">تایید شماره تلفن</h5>
                    <p class="center">کد ارسالی به شماره موبایل خود را وارد کنید</p>
                    <form class="form" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <input id="id_confirmation_code" name="id_confirmation_code" type="text"
                                       class="validate" pattern="^\d{6}$" title="کد تایید شامل 6 رقم میباشد.">
                                <label for="id_confirmation_code">کد تایید</label>
                                <span class="helper-text" data-error="غلطه" data-success="حله"></span>
                            </div>
                        </div>
                        <button class="waves-effect waves-light btn" type="submit" name="button">ارسال</button>
                    </form>
                </div>
                <a href="{% url 'sms:resend' %}" class="right">ارسال دوباره کد</a>
            </div>
        </div>

    </main>


{% endblock %}



{% block my_footer_script %}
    <script type="text/javascript" src="{% static 'js/profileimage.js' %}"></script>

{% endblock %}

users/templates/users/create.html
{% load static %}
{% if user.is_authenticated %}
    {% extends 'authenticated.html' %}

{% endif %}

users/templates/users/dashboard.html
{% extends 'authenticated.html' %}
{% load static %}

{% block title %}داشبورد{% endblock %}
{% block content %}

    <main>

        <div class="container">

            <div class="row userD">

                <div class="col s12">
                    {% if not user.is_verified %}
                        <div class="card emailerror2">

                            <p class="emailp"> شما ایمیل خود را تایید نکردید. <a href="{% url 'emails:resend_email' %}">ارسال
                                مجدد</a></p>


                        </div>
                    {% endif %}
                    {% if not user.is_phone_number_verified %}
                        <div class="card emailerror2">

                            <p class="emailp"> شما موبایل خود را تایید نکردید. <a
                                    href="{% url 'users:confirm_phone_number' %}">تایید شماره موبایل
                            </a></p>


                        </div>
                    {% endif %}
                </div>


                <div class="col s12 m6 l6">
                    <div class="card small card-medium">
                        <div class="card-content">
                            <div class="row middle-row">
                                <div class="col s4">
                                    <div class="card-image imageDashboard imageda2">
                                        <a href="/users/profile/">
                                            <img {% if  user.profile_picture %}
                                                src="{% get_media_prefix %}{{ user.profile_picture }}"
                                            {% else %}
                                                src='{% static "assets/default.png" %}'
                                            {% endif %}>
                                        </a>
                                    </div>
                                </div>

                                <div class="col s8 vertical-al" style="margin-top: 20px;">
                                    <h6 id="wallet" class="right">{{ user.wallet.amount }} <span>اطلاعات تماس شما</span>
                                    </h6>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s4">
                                    <p id="wtext" class="center right">:موبایل</p>
                                </div>
                                <div class="col s8">
                                    {{ user.phone_number }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s4">
                                    <p id="wtext" class="center right">:ایمیل</p>
                                </div>
                                <div class="col s8">
                                    {{ user.email }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s4">
                                    <p id="wtext" class="center right">:تلگرام</p>
                                </div>
                                <div class="col s8">
                                    {% if user.telegram %}
                                        <a href="https://t.me/{{ user.telegram }}"
                                           target="_blank">{{ user.telegram }}</a>
                                    {% else %}
                                        وارد نشده
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s4">
                                    <p id="wtext" class="center right">:اینستاگرام</p>
                                </div>
                                <div class="col s8">
                                    {% if user.instagram %}
                                        <a href="https://instagram.com/{{ user.instagram }}"
                                           target="_blank">@{{ user.instagram }}</a>
                                    {% else %}
                                        وارد نشده
                                    {% endif %}
                                </div>
                            </div>


                            <a class="waves-effect waves-light btn-small request center modal-trigger"
                               href="{% url 'users:profile' %}" style="width: 40%;">ویرایش</a>

                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l6">
                    <div class="card small card-medium">
                        <div class="card-content">
                            <div class="row middle-row">
                                <div class="col s12 vertical-al" style="margin-top: 20px;margin-bottom: 20px;">
                                    <h6 id="wallet" class="center">{{ user.wallet.amount }} <span>اطلاعات آگهی های شما</span>
                                    </h6>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s4">
                                    <p id="wtext" class="center ">:آگهی شرکت</p>
                                </div>
                                <div class="col s8">
                                    {{ user_ads }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s4">
                                    <p id="wtext" class="center ">:آگهی تامین مهندس</p>
                                </div>
                                <div class="col s8">
                                    {{ user_en_ads }}
                                </div>
                            </div>


                            <a class="waves-effect waves-light btn-small request center modal-trigger"
                               href="{% url 'advertises:my_list' %}" style="width: 40%;margin-top: 111px;">مشاهده</a>

                        </div>
                    </div>
                </div>

    </main>

    <div class="hide">
        {{ request.path }}
    </div>


{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main>

        <div class="row login1">
            <div class="col s12">
                <div class="card-panel white">
                    <h5 class="center">ورود</h5>
                    <p class="center">برای ورود آدرس ایمیل و رمز عبور خود را وارد کنید.</p>
                    <form class="form" method="post">
                        {% csrf_token %}

                        <div class="row">
                            <div class="input-field col s12">
                                {#                                <input id="email" type="email" class="validate">#}
                                <label for="id_email">ایمیل</label>
                                {{ form.email }}

                                {% if form.email.errors %}
                                    <span class="helper-text" data-error="{{ form.email.errors.as_text }}"
                                          data-success="حله!"></span>
                                {% else %}
                                    <span class="helper-text" data-error="ایمیل غلطه" data-success="حله!"></span>
                                {% endif %}


                            </div>
                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                                <label for="id_password">پسورد</label>

                                {{ form.password }}
                                {% if form.password.errors %}
                                    <span class="helper-text" data-error="{{ form.password.errors.as_text }}"
                                          data-success="حله!"></span>
                                {% else %}
                                    <span class="helper-text" data-error="پسورد شامل عدد و حروفه از 4 تا 24 حرف"
                                          data-success="حله!"></span>
                                {% endif %}

                            </div>
                        </div>
                        <button class="waves-effect waves-light btn font" type="submit" name="button">ورود</button>
                    </form>
                </div>
            </div>
            <div class="center"><a href="{% url 'users:forgot_password' %}">رمز عبور رو فراموش کردی؟</a></div>
        </div>

    </main>


{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main>

        <div class="container">
            <div class="row login1">
                <div class="col s12 center">

                    <div class="card-panel white" style="text-align: right">
                       پسورد شما ریست شد. لطفا برگردید و لاگین کنید.
                    </div>
                    <a class="center" href="{% url 'users:login' %}">بازگشت</a>
                </div>
            </div>
        </div>
    </main>


{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main>

        <div class="row login1">
            <div class="col s12">
                <div class="card-panel white">
                    {{ field.errors }}
                    {{ form.non_field_errors }}

                    <h5 class="center">ثبت نام</h5>
                    <p class="center">برای ثبت نام آدرس ایمیل و رمز عبور انتخابی خود را وارد کنید.</p>
                    <form class="form" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <label for="id_email">ایمیل</label>
                                {{ form.email }}

                                {% if form.email.errors %}
                                    <span class="helper-text" data-error="{{ form.email.errors.as_text }}"
                                          data-success="حله!"></span>
                                {% else %}
                                    <span class="helper-text" data-error="ایمیل غلطه" data-success="حله!"></span>
                                {% endif %}


                            </div>
                        </div>


                        <div class="row">
                            <div class="input-field col s12">
                                <label for="id_phone_number">موبایل</label>
                                {{ form.phone_number }}

                                {% if form.phone_number.errors %}
                                    <span class="helper-text" data-error="{{ form.phone_number.errors.as_text }}"
                                          data-success="حله!"></span>
                                {% else %}
                                    <span class="helper-text" data-error="شماره موبایل غلطه" data-success="حله!"></span>
                                {% endif %}


                            </div>
                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                                <label for="id_password">پسورد</label>

                                {{ form.password }}
                                <span class="helper-text" data-error="پسورد شامل عدد و حروفه از 4 تا 24 حرف"
                                      data-success="حله!"></span>
                            </div>
                        </div>
                        <div class="row">
                            <p>
                                <label>
                                    {{ form.privacy }}
                                    <span>با <a
                                            href="{% url 'publics:privacy_policy' %}">قوانین و مقررات</a> موافقم</span>
                                </label>
                            </p>
                        </div>
                        <button class="waves-effect waves-light btn font" type="submit" name="button">ثبت نام</button>
                    </form>
                </div>
            </div>
        </div>

    </main>


{% endblock %}

users/templates/users/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>okeye</h1>
</body>
</html>