advertises/urls.py
from django.urls import path
from . import views

app_name = 'advertises'

urlpatterns = [
    path('list/', views.AdvertisesList.as_view(), name='list'),
    path('mine/', views.MyAdvertisesList.as_view(), name='my_list'),
    path('<int:pk>/', views.AdvertiseDetail.as_view(), name='detail'),
    path('create/', views.CreateAd.as_view(), name='create'),
    path('statistic/<int:pk>/', views.Statistic.as_view(), name='statistic'),
    path('update/<int:pk>/', views.UpdateAdvertise.as_view(), name='update'),
    # path('<int:pk>/questions_edit/', views.QuestionsEdit.as_view(), name='questions_edit'),
    path('fake/', views.create_fake_ads, name='fake'),

]

company_advertise_invoice/urls.py
from django.urls import path, re_path
from . import views

app_name = 'ca_invoice'
urlpatterns = [
    path('create/', views.CreateCAInvoice, name='create'),
    path('history/', views.InvoiceHistory.as_view(), name='history'),
    path('<str:type>/<int:pk>/', views.GetInvoice.as_view(), name='get'),
]

publics/urls.py
from django.urls import path
from . import views

app_name = 'publics'

urlpatterns = [
    path('', views.root, name='root'),
    path('about_us/', views.about_us, name='about_us'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('support/', views.support, name='support'),
]

sabtika/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('publics.urls', namespace='publics')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('emails/', include('emails.urls', namespace='emails')),
    path('advertises/', include('advertises.urls', namespace='advertises')),
    path('engineer/', include('engineer_advertises.urls', namespace='engineer_advertises')),
    path('withdrawal/', include('withdrawal.urls', namespace='withdrawal')),
    path('ca_invoice/', include('company_advertise_invoice.urls', namespace='ca_invoice')),
    path('en_invoice/', include('engineer_advertise_invoice.urls', namespace='en_invoice')),
    path('sms/', include('sms.urls', namespace='sms')),
    path('gateway/', include('gateway.urls', namespace='gateway')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
from django.urls import path
from . import views

app_name = 'sms'
urlpatterns = [
    path('resend/', views.resend_confirm_code, name='resend')
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('signup/', views.SignupUsersView.as_view(), name='signup'),
    path('login/', views.LoginUser, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.ProfileUsersView.as_view(), name='profile'),
    path('profile/confirm_phone_number', views.confirm_phone_number, name='confirm_phone_number'),
    path('bank_info/', views.UpdateBankInfo, name='bank_info'),
    path('forgot_password/', views.MyPasswordRestartView.as_view(), name='forgot_password'),
    path('password_reset_confirm/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_done/', views.MyPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset_complete/', views.MyPasswordResetCompleteView.as_view(),
             name='password_reset_complete'),


]

templates/authenticated.html
{% extends 'base.html' %}

{% load static %}



{% block messages %}

    {{ block.super }}

{% endblock %}

{% block form_errors %}

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}


                <div class="col s12">
                    <div class="card emailerror">

                        <p class="emailp">                    {{ field.name }}:{{ error|escape }}</p>


                    </div>
                </div>

            {% endfor %}
        {% endfor %}

    {% endif %}

{% endblock %}




{% block footer_menu %}

{% endblock %}

templates/base.html
{% load static %}
{% block upper_html %}

    <!DOCTYPE html>
    <html lang="en" dir="rtl">
    <head>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %} "
              media="screen,projection "/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.rtl.min.css' %}"
              media="screen,projection"/>
        <link rel="icon" href="" type="image/png" sizes="16x16">
        <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}?hjghjghj"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/sabtika-main.css' %}?3sdfasdgasdsdf43"/>

        <link rel="stylesheet" type="text/css" href="{% static 'slick/slick.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'slick/slick-theme.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'slick/slickmain.css' %}"/>

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <meta charset="utf-8">
        <meta http-equiv="Expires" content="Mon, 26 Jul 1997 05:00:00 GMT">
        <meta http-equiv="Pragma" content="no-cache">
        {% block my_scripts %}

        {% endblock %}
        <title>{% block title %}ثبتیکا |آگهی شرکت ها، نیازمندی های شرکت ها{% endblock %}</title>

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-138319229-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-138319229-1');
        </script>

        <!-- Crisp chat script -->
        <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="786c72f4-5cf9-41f9-96c3-addcdb90a72d";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

    </head>

    <body>
    {% block body %}
        {% url 'users:login' as login %}
        {% url 'users:signup' as signup %}
        {% url 'users:dashboard' as dashboard %}
        {% url 'publics:root' as root %}
        {% url 'publics:about_us' as about_us %}
        {% url 'publics:privacy_policy' as privacy_policy %}
        {% url 'advertises:list' as advertises_list %}
        {% url 'engineer_advertises:list' as engineer_advertises_list %}
        {% url 'advertises:my_list' as my_advertises_list %}
        {% url 'engineer_advertises:my_list' as my_engineer_advertises_list %}
        {% url 'ca_invoice:history' as ca_invoice_history %}
        {% url 'en_invoice:history' as en_invoice_history %}
        <header>
            {% block header %}
                {% if user.is_authenticated %}

                    <nav id="menuNav">
                        <div class="nav-wrapper">

                            {#        <img src="assets/logo.png" alt="" class="logo1">#}
                            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i
                                    class="material-icons">menu</i></a>
                            <ul class="right hide-on-med-and-down">
                                <li {% if request.path == root %}
                                    class="active"
                                {% endif %}><a href="{% url 'publics:root' %}">خانه</a></li>
                                <li {% if request.path == advertises_list or request.path == engineer_advertises_list %}
                                    class="active"
                                {% endif %}><a href="{% url 'advertises:list' %}">آگهی ها</a></li>
                                <li
                                        {% if request.path == my_advertises_list or request.path == my_engineer_advertises_list %}
                                            class="active"
                                        {% endif %}><a href="{% url 'advertises:my_list' %}">آگهی های من</a></li>
                                <li {% if request.path == ca_invoice_history or request.path == en_invoice_history %}
                                    class="active"
                                {% endif %}><a href="{% url 'ca_invoice:history' %}">تراکنش های من</a></li>
                                <li {% if request.path == dashboard %}
                                    class="active"
                                {% endif %}><a href="{% url 'users:dashboard' %}">داشبورد</a></li>
                                <li><a href="{% url 'users:logout' %}">خروج</a></li>


                            </ul>
                        </div>

                        <ul class="sidenav right" id="mobile-demo">
                            <li {% if request.path == root %}
                                class="active"
                            {% endif %}><a href="{% url 'publics:root' %}">خانه</a></li>
                            <li {% if request.path == advertises_list or request.path == engineer_advertises_list %}
                                class="active"
                            {% endif %}><a href="{% url 'advertises:list' %}">آگهی ها</a></li>
                            <li
                                    {% if request.path == my_advertises_list or request.path == my_engineer_advertises_list %}
                                        class="active"
                                    {% endif %}><a href="{% url 'advertises:my_list' %}">آگهی های من</a></li>
                            <li {% if request.path == ca_invoice_history or request.path == en_invoice_history %}
                                class="active"
                            {% endif %}><a href="{% url 'ca_invoice:history' %}">تراکنش های من</a></li>
                            <li {% if request.path == dashboard %}
                                class="active"
                            {% endif %}><a href="{% url 'users:dashboard' %}">داشبورد</a></li>
                            <li><a href="{% url 'users:logout' %}">خروج</a></li>

                        </ul>

                    </nav>
                {% else %}
                    <nav id="menuNav">
                        <div class="nav-wrapper">

                            {#        <img src="assets/logo.png" alt="" class="logo1">#}
                            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i
                                    class="material-icons">menu</i></a>
                            <ul class="right hide-on-med-and-down">
                                <li {% if request.path == root %}
                                    class="active"
                                {% endif %}><a href="{% url 'publics:root' %}">خانه</a></li>
                                <li {% if request.path == about_us %}
                                    class="active"
                                {% endif %}><a href="{% url 'publics:about_us' %}"> درباره ما</a></li>
                                <li {% if request.path == privacy_policy %}
                                    class="active"
                                {% endif %}><a href="{% url 'publics:privacy_policy' %}"> قوانین</a></li>
                                <li {% if request.path == login %}
                                    class="active"
                                {% endif %}><a href="{% url 'users:login' %}">ورود</a></li>
                                <li {% if request.path == signup %}
                                    class="active"
                                {% endif %}><a href="{% url 'users:signup' %}">ثبت نام</a></li>
                            </ul>
                        </div>

                        <ul class="sidenav right" id="mobile-demo">
                            <li {% if request.path == root %}
                                class="active"
                            {% endif %}><a href="{% url 'publics:root' %}">خانه</a></li>
                            <li {% if request.path == about_us %}
                                class="active"
                            {% endif %}><a href="{% url 'publics:about_us' %}"> درباره ما</a></li>
                            <li {% if request.path == privacy_policy %}
                                class="active"
                            {% endif %}><a href="{% url 'publics:privacy_policy' %}"> قوانین</a></li>
                            <li {% if request.path == login %}
                                class="active"
                            {% endif %}><a href="{% url 'users:login' %}">ورود</a></li>
                            <li {% if request.path == signup %}
                                class="active"
                            {% endif %}><a href="{% url 'users:signup' %}">ثبت نام</a></li>
                        </ul>

                    </nav>

                {% endif %}




                {% block messages %}
                    {#                    {% if messages %}#}
                    {#                        {% for message in messages %}#}
                    {#                            <div class="col s12">#}
                    {#                                <div class="card emailerror">#}
                    {##}
                    {#                                    <p class="emailp">{{ message }}</p>#}
                    {##}
                    {##}
                    {#                                </div>#}
                    {#                            </div>#}
                    {#                        {% endfor %}#}
                    {#                    {% endif %}#}
                {% endblock %}

            {% endblock %}
        </header>

        {% block content %}

        {% endblock %}
        {% block footer %}
            {% block footer_menu %}
                <footer class="s12 ftest">
                    <div class="divider"></div>
                    <ul id="horizontal-list2">
                        <li><a id="after4" class="grey-text text-lighten-3 font" href="{% url 'publics:root' %}"> صفحه
                            اصلی </a></li>
                        <li><a id="after2" class="grey-text text-lighten-3 font" href="{% url 'publics:about_us' %}">
                            درباره ما </a>
                        </li>
                        <li><a id="after3" class="grey-text text-lighten-3 font"
                               href="{% url 'publics:support' %}"> پشتیبانی </a>
                        </li>
                        <li><a id="after3" class="grey-text text-lighten-3 font"
                               href="{% url 'publics:privacy_policy' %}"> قوانین </a>
                        </li>
                    </ul>
                </footer>
            {% endblock %}



            <script type="text/javascript" src="{% static 'slick/slick.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'js/myslick.js' %}"></script>
            <!--JavaScript at end of body for optimized loading-->
            <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'js/main.js' %}"></script>



            {% if messages %}
                {% for message in messages %}
                    <script type="text/javascript">

                        M.toast({html: '{{ message }}', displayLength: 10000});

                    </script>


                {% endfor %}
            {% endif %}
            {% block my_footer_script %}

            {% endblock %}
        {% endblock %}

    {% endblock %}
    </body>


    </html>

{% endblock %}