advertises/urls.py
from django.urls import path
from . import views

app_name = 'advertises'

urlpatterns = [
    path('list/', views.AdvertisesList.as_view(), name='list'),
    path('mine/', views.MyAdvertisesList.as_view(), name='my_list'),
    path('<int:pk>/', views.AdvertiseDetail.as_view(), name='detail'),
    path('create/', views.CreateAd.as_view(), name='create'),
    path('statistic/<int:pk>/', views.Statistic.as_view(), name='statistic'),
    path('update/<int:pk>/', views.UpdateAdvertise.as_view(), name='update'),
    # path('<int:pk>/questions_edit/', views.QuestionsEdit.as_view(), name='questions_edit'),
    path('fake/', views.create_fake_ads, name='fake'),

]

sabtika/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('publics.urls', namespace='publics')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('emails/', include('emails.urls', namespace='emails')),
    path('advertises/', include('advertises.urls', namespace='advertises')),
    path('engineer/', include('engineer_advertises.urls', namespace='engineer_advertises')),
    path('withdrawal/', include('withdrawal.urls', namespace='withdrawal')),
    path('ca_invoice/', include('company_advertise_invoice.urls', namespace='ca_invoice')),
    path('en_invoice/', include('engineer_advertise_invoice.urls', namespace='en_invoice')),
    path('sms/', include('sms.urls', namespace='sms')),
    path('gateway/', include('gateway.urls', namespace='gateway')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
from django.urls import path
from . import views

app_name = 'sms'
urlpatterns = [
    path('resend/', views.resend_confirm_code, name='resend')
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('signup/', views.SignupUsersView.as_view(), name='signup'),
    path('login/', views.LoginUser, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.ProfileUsersView.as_view(), name='profile'),
    path('profile/confirm_phone_number', views.confirm_phone_number, name='confirm_phone_number'),
    path('bank_info/', views.UpdateBankInfo, name='bank_info'),
    path('forgot_password/', views.MyPasswordRestartView.as_view(), name='forgot_password'),
    path('password_reset_confirm/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_done/', views.MyPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset_complete/', views.MyPasswordResetCompleteView.as_view(),
             name='password_reset_complete'),


]

advertises/models.py
from django.db import models
from users.models import Users
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from .constants import CITIES, COMPANY_TYPES, ADVERTISE_TYPE


# Create your models here.
class Advertises(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=1000, null=True)
    type = models.CharField(choices=COMPANY_TYPES, max_length=30)
    register_year = models.IntegerField(validators=[MinValueValidator(1340), MaxValueValidator(1398)])
    register_location = models.CharField(choices=CITIES, max_length=30)
    financial_code = models.BooleanField()
    price = models.DecimalField(decimal_places=0, max_digits=12)
    creation_date = models.DateTimeField(auto_now_add=True)
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], null=True, blank=True)
    company_pic = models.ImageField(null=True, blank=True)
    is_approved = models.BooleanField(default=False)
    email_contact = models.BooleanField(default=False)
    mobile_contact = models.BooleanField(default=False)
    ladder_date = models.DateTimeField()
    urgent = models.BooleanField(default=False)
    advertise_type = models.CharField(choices=ADVERTISE_TYPE, max_length=30)

    def get_absolute_url(self):
        if self.companyadvertiseinvoice.payment:
            return (reverse('advertises:my_list'))
        else:
            return (reverse('ca_invoice:get', kwargs={'pk': self.companyadvertiseinvoice.id, 'type': 'regular'}))
            #
            # @staticmethod
            # def is_owner(pk, user):
            #     # return Advertises.objects.filter(pk=pk).first().user == user
            #     user_test = Advertises.objects.get(pk=pk)
            #     return user_test.user == user
            #
            # def calculate_amount_for_invoice(self):
            #     return (self.users_number * self.per_user_price) + (self.questions_number * self.per_question_price)
            #
            # def save(self, force_insert=False, force_update=False, using=None,
            #          update_fields=None):
            #     db_us = Advertises.objects.filter(pk=self.pk).first()
            #
            #     if db_us != None:
            #         update_fields = []
            #         if db_us.questions_number != self.questions_number:
            #             update_fields = ['questions_number']
            #
            #         if db_us.users_number != self.users_number:
            #             update_fields.append('users_number')
            #
            #         if db_us.title != self.title:
            #             update_fields.append('title')
            #
            #         if update_fields == []:
            #             update_fields = None
            #
            #     return super(Advertises, self).save(force_insert=False, force_update=False, using=None,
            #                                        update_fields=update_fields)

advertises/forms.py
from django import forms
from django.forms import ModelForm
from .models import Advertises
from django.utils.translation import gettext as _


class CreateAdvertiseForm(ModelForm):
    # questions_number = forms.IntegerField(widget=forms.NumberInput(attrs={'type':'range', 'step': '2'}))
    has_grade = forms.BooleanField()
    accuracy = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        super(CreateAdvertiseForm, self).__init__(*args, **kwargs)
        self.fields['grade'].widget.attrs = {"min": "1", "max": "5", "step": "1",
                                             'class': 'users_number_input', 'disabled': 'disabled'}
        self.fields['register_year'].widget.attrs = {"min": "1358", "max": "1397", "step": "1",
                                                     'class': 'questions_number_input'}
        self.fields['description'].widget.attrs = {'class': 'materialize-textarea'}
        self.fields['has_grade'].required = False
        self.fields['financial_code'].required = False

    class Meta:
        model = Advertises
        fields = ['company_name', 'description', 'type', 'register_year', 'register_location', 'financial_code',
                  'price', 'grade', 'has_grade', 'company_pic', 'advertise_type']
        widgets = {
            'grade': forms.NumberInput(attrs={'type': 'range'}),
            'register_year': forms.NumberInput(attrs={'type': 'range'}),
            'description': forms.Textarea,
        }


class UpdateAdvertiseForm(ModelForm):
    # questions_number = forms.IntegerField(widget=forms.NumberInput(attrs={'type':'range', 'step': '2'}))
    has_grade = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        super(UpdateAdvertiseForm, self).__init__(*args, **kwargs)
        self.fields['grade'].widget.attrs = {"min": "1", "max": "5", "step": "1",
                                             'class': 'users_number_input', 'disabled': 'disabled'}
        self.fields['register_year'].widget.attrs = {"min": "1358", "max": "1397", "step": "1",
                                                     'class': 'questions_number_input'}
        self.fields['description'].widget.attrs = {'class': 'materialize-textarea'}
        self.fields['has_grade'].required = False
        self.fields['financial_code'].required = False

    class Meta:
        model = Advertises
        fields = ['company_name', 'description', 'type', 'register_year', 'register_location', 'financial_code',
                  'price', 'grade', 'has_grade', 'company_pic', 'advertise_type']
        widgets = {
            'grade': forms.NumberInput(attrs={'type': 'range'}),
            'register_year': forms.NumberInput(attrs={'type': 'range'}),
            'description': forms.Textarea,
        }

advertises/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from .models import Advertises
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import CreateAdvertiseForm, UpdateAdvertiseForm
from publics.decorators import mobile_confirmed_required
from .decorators import owner_required
from django.shortcuts import render
from faker import Faker
from django.http import HttpResponse
from .constants import COMPANY_TYPES, CITIES, ADVERTISE_TYPE
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import redirect


# Create your views here.

class AdvertisesList(ListView):
    # page_template = 'advertises/list_page.html'
    template_name = 'advertises/list.html'
    paginate_by = 10

    # @method_decorator(login_required)
    # @method_decorator(mobile_confirmed_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):

        filters = {}
        if 'financial-code-checkbox' in self.request.GET:
            if self.request.GET['financial-code-checkbox'] == 'on':
                filters['financial_code'] = True

        if 'company-type' in self.request.GET:
            filters['type'] = self.request.GET['company-type']

        if 'city' in self.request.GET:
            filters['city'] = self.request.GET['city']

        if 'year-from' in self.request.GET:
            filters['register_year__gte'] = self.request.GET['year-from']

        if 'year-to' in self.request.GET:
            filters['register_year__lte'] = self.request.GET['year-to']

        if 'grade-from' in self.request.GET:
            filters['grade__gte'] = self.request.GET['grade-from']

        if 'grade-to' in self.request.GET:
            filters['grade__lte'] = self.request.GET['grade-to']

        if 'price-from' in self.request.GET:
            filters['price__gte'] = self.request.GET['price-from']

        if 'price-to' in self.request.GET:
            filters['price__lte'] = self.request.GET['price-to']

        if 'advertise-type' in self.request.GET:
            filters['advertise_type'] = self.request.GET['advertise-type']

        if filters == {}:
            return Advertises.objects.filter(companyadvertiseinvoice__payment__exact=True).order_by('-ladder_date')
        else:
            return Advertises.objects.filter(**filters, companyadvertiseinvoice__payment__exact=True).order_by(
                '-ladder_date')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(AdvertisesList, self).get_context_data(object_list=None, **kwargs)
        # add first pic of first question to tests
        context['company_types'] = COMPANY_TYPES
        context['cities'] = CITIES
        context['advertise_type'] = ADVERTISE_TYPE

        for obj in context['object_list']:
            obj.price = format(int(obj.price), ",d")

        return context

    def get(self, request, *args, **kwargs):

        return super(AdvertisesList, self).get(request, *args, **kwargs)


class MyAdvertisesList(ListView):
    # page_template = 'advertises/list_page.html'
    template_name = 'advertises/my-list.html'
    paginate_by = 10

    @method_decorator(login_required)
    # @method_decorator(email_confirmed_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return Advertises.objects.filter(user=self.request.user).order_by('-ladder_date')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MyAdvertisesList, self).get_context_data(object_list=None, **kwargs)
        # add first pic of first question to tests
        context['company_types'] = COMPANY_TYPES
        context['cities'] = CITIES

        return context


class CreateAd(CreateView):
    form_class = CreateAdvertiseForm
    queryset = Advertises.objects.all()
    template_name = 'advertises/create.html'

    @method_decorator(login_required)
    @method_decorator(mobile_confirmed_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        # if not request.user.first_name or not request.user.profile_picture:
        #     messages.add_message(self.request, messages.ERROR,
        #                          _('Your have to set your profile picture and name first! '))
        #     return redirect('users:profile', pk=request.user.id)

        return super(CreateAd, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        if form.cleaned_data['accuracy'] != True:
            messages.add_message(self.request, messages.ERROR, 'شما باید قوانین و مقررات را قبول کنید.')
            return redirect('advertises:create')
        form.instance.user = self.request.user

        now = timezone.now()
        form.instance.ladder_date = now

        return super(CreateAd, self).form_valid(form)


class UpdateTest(UpdateView):
    form_class = CreateAdvertiseForm
    queryset = Advertises.objects.all()
    template_name = 'advertises/update_test.html'

    @method_decorator(login_required)
    @method_decorator(mobile_confirmed_required)
    @method_decorator(owner_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(UpdateTest, self).form_valid(form)


class Statistic(DetailView):
    model = Advertises
    template_name = 'advertises/statistics.html'

    @method_decorator(login_required)
    @method_decorator(mobile_confirmed_required)
    @method_decorator(owner_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


        # def get_context_data(self, **kwargs):
        # context = super(Statistic, self).get_context_data(**kwargs)
        # questions = Questions.objects.filter(test=kwargs['object'])
        # for q in questions:
        #     q.count_of_first_pic = Answers.objects.filter(question=q,answer='1').count()
        #     q.count_of_second_pic = Answers.objects.filter(question=q,answer='2').count()
        #
        # context['question_list'] = questions
        # return context


class AdvertiseDetail(DetailView):
    model = Advertises
    template_name = 'advertises/detail.html'

    # @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AdvertiseDetail, self).get_context_data(**kwargs)
        context['object'].price = format(int(context['object'].price), ",d")
        return context
        #
        # def get_context_data(self, **kwargs):
        #     context = super(QuestionsEdit, self).get_context_data(**kwargs)
        #     questions = Questions.objects.filter(test=kwargs['object'])
        #
        #     context['question_list'] = questions
        #     return context


class UpdateAdvertise(UpdateView):
    form_class = UpdateAdvertiseForm
    queryset = Advertises.objects.all()
    template_name = 'advertises/update.html'

    @method_decorator(login_required)
    @method_decorator(mobile_confirmed_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def create_fake_ads(request):
    user = request.user
    fake = Faker()
    for i in range(int(request.GET['num'])):
        company_name = fake.name()
        description = 'same'
        type = 1
        register_year = 1392
        register_location = 2
        financial_code = 1
        price = 20000
        ad = Advertises.objects.create(user=user, company_name=company_name, description=description, type=type,
                                       register_year=register_year, register_location=register_location,
                                       financial_code=financial_code, price=price)

    return HttpResponse('ok')


def ajax_list(request):
    # numbers_list = range(1, 1000)
    # page = request.GET.get('page', 1)
    # paginator = Paginator(numbers_list, 20)
    # try:
    #     numbers = paginator.page(page)
    # except PageNotAnInteger:
    #     numbers = paginator.page(1)
    # except EmptyPage:
    #     numbers = paginator.page(paginator.num_pages)
    return render(request, 'advertises/list_page.html')

advertises/templates/advertises/detail.html
{% extends 'authenticated.html' %}
{% load static %}


{% block content %}
    <main>


        <div class="row createtest detail-createtest">
            <div class="col s12" style="height: 400px">
                <div class="card-panel white" style="padding-bottom: 58px">


                    <div class="row ">
                        <div class="col s12 center center">
                            <img class="imga" src="{% get_media_prefix %}{{ object.company_pic }}" alt=""
                                 style="margin-right: 0px">

                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12 detail-title center">
                            <h5 class="center"> {{ object.company_name }}</h5>
                        </div>
                    </div>
                    <div class="font2 otext " style="color: #ad1457">
                                        <div class="row">
                                            <div class="col s8">
نوع آگهی: {{ object.get_advertise_type_display }}
<img class="image-header-icon" src="{% if object.advertise_type == '1' %}{% static 'assets/purchase.png' %}{% elif object.advertise_type == '2' %}{% static 'assets/wanted.png' %}{% endif %}" alt="">
                                            </div>
                                        </div>
                    </div>
                    <div class="row">
                        <div class="col s4"><p class="font2 detail-text ">نوع شرکت:</p></div>
                        <div class="col s8"><p class="font2 detail-text ">{{ object.get_type_display }}</p></div>
                    </div>
                    <div class="row">
                        <div class="col s4"><p class="font2 detail-text ">سال تاسیس:</p></div>
                        <div class="col s8"><p class="font2 detail-text ">{{ object.register_year }}</p></div>
                    </div>
                    <div class="row">
                        <div class="col s4"><p class="font2 detail-text ">کد اقتصادی:</p></div>
                        <div class="col s8"><p class="font2 detail-text ">{% if object.financial_code %}
                            دارد
                        {% else %}
                            ندارد
                        {% endif %}</p></div>
                    </div>
                    <div class="row">
                        <div class="col s4"><p class="font2 detail-text ">گرید:</p></div>
                        <div class="col s8"><p class="font2 detail-text ">{% if object.grade == None %}
                            ندارد
                        {% else %}
                            {{ object.grade }}
                        {% endif %}</p></div>
                    </div>
                    <div class="row">
                        <div class="col s4"><p class="font2 detail-text ">قیمت:</p></div>
                        <div class="col s8"><p class="font2 detail-text "><span class="price">{{ object.price }}</span>
                            تومان</p></div>
                    </div>

                    <div class="row">
                        <div class="col s4"><p class="font2 detail-text ">توضیحات:</p></div>
                        <div class="col s8"><p class="break-word font2 detail-text ">{{ object.description }}</p></div>
                    </div>

                    <div class="divider"></div>
                    <br>
                    <div class="col s2"></div>
                    <div class="col s8 center">
                        <a class="waves-effect waves-light btn-small pro center modal-trigger"
                           href="#contact-detail-modal" style="width:70%;">اطلاعات تماس</a>
                    </div>
                    <div class="col s2"></div>


                </div>


            </div>


        </div>
        {% if user.is_authenticated %}
            <div id="contact-detail-modal" class="modal detail-modal" tabindex="0"
                 style="z-index: 1003; display: block; opacity: 1; top: 10%; transform: scaleX(1) scaleY(1);">
                <form class="form" action="/withdrawal/create/" method="post">
                    <input type="hidden" name="csrfmiddlewaretoken"
                           value="4TgKdDEUARZsNvWegWKegABIl8p0BXG3ogx9XIgaXpNEatk8IJLh5rH08QCiGYh3">
                    <input type="hidden" id="user" name="user" value="4">
                    <div class="modal-content">
                        <h5 id="wallet" class="center">اطلاعات تماس</h5>
                        <div class="row">
                            <div class="col s4"><p class="font2 detail-text ">ایمیل:</p></div>
                            <div class="col s8"><p class="font2 detail-text ">{% if object.user.email != None %}
                                {{ object.user.email }}
                            {% else %}
                                ندارد

                            {% endif %}</p></div>

                            <div class="col s4"><p class="font2 detail-text ">موبایل:</p></div>
                            <div class="col s8"><p class="font2 detail-text ">
                                {% if  object.user.phone_number != None %}
                                    {{ object.user.phone_number }}
                                {% else %}
                                    ندارد

                                {% endif %}</p></div>


                            {% if  object.user.instagram != None %}
                                <div class="col s4"><p class="font2 detail-text ">اینستاگرام:</p></div>
                                <div class="col s8"><p class="font2 detail-text ">
                                    <a href="https://instagram.com/{{ object.user.instagram }}"
                                       target="_blank">{{ object.user.instagram }}</a>
                                </p></div>{% endif %}


                            {% if  object.user.telegram != None %}
                                <div class="col s4"><p class="font2 detail-text ">تلگرام:</p></div>
                                <div class="col s8"><p class="font2 detail-text ">
                                    <a href="https://t.me/{{ object.user.telegram }}"
                                       target="_blank">{{ object.user.telegram }}</a>
                                </p></div>{% endif %}


                        </div>
                    </div>
                    <div class="modal-footer" style="text-align: center;">
                        <button type="button"
                                class="waves-effect waves-light btn-small center modalbtn font modal-close">
                            بستن
                        </button>
                    </div>
                </form>
            </div>
        {% else %}
            <div id="contact-detail-modal" class="modal detail-modal" tabindex="0"
                 style="z-index: 1003; display: block; opacity: 1; top: 10%; transform: scaleX(1) scaleY(1);">
                <div class="container">
                    <div class="row">
                        <p>برای مشاهده اطلاعات تماس شما باید در وبسایت ثبت نام کنید یا اگر قبلا ثبت نام کرده اید، وارد
                            شوید.</p>
                        <div class="row">
                            <div class="col s6 left"><p><a href="{% url 'users:signup' %}">ثبت نام</a></p>
                            </div>
                            <div class="col s6 right"><p class="left" style="margin-left: 10px;"><a
                                    href="{% url 'users:login' %}">ورود</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </main>

{% endblock %}
{##}
{#{% block my_footer_script %}#}
{#    <script type="text/javascript" src="{% static 'js/add-commas-to-digits.js' %}"></script>#}
{#    <script>#}
{#        $("span.price").digits();#}
{#    </script>#}
{#{% endblock %}#}

advertises/templates/advertises/list_page.html
{% extends 'authenticated.html' %}
{% load static %}
{% block my_scripts %}

    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    <script src="{% static 'js/nouislider.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/nouislider.css' %}">


{% endblock %}
{% block content %}
    <form action="" method="get">

        <select name="one" id="one1">
            <option value="a">aa</option>
            <option value="b">bb</option>
        </select>
        <input type="submit" value="asdasd" name="asd">
    </form>
{% endblock %}



{% block my_footer_script %}


{% endblock %}

advertises/templates/advertises/mytests.html
{% extends 'authenticated.html' %}
{% load static %}


{% block content %}
    <main>

        <div class="container">

            <div class="row userD">
                <div class="col s8">
                    <div class="card right">

                        <div class="card-content myTestsCo">
                            <div class="col s3 s3test">
                                <img src="{% if user.profile_picture %}
                                    {% get_media_prefix %}{{ user.profile_picture }}
                                    {% else %}
                                        {% static 'assets/default.png' %}
                                    {% endif %}
                                    " alt=""
                                     class="circle responsive-img">
                                <!-- notice the "circle" class -->
                            </div>
                            <div class="col s9 rtl">
                <span class="black-text">
                  {% if not user.first_name %}
                      نام خود را انتخاب کنید
                  {% else %}
                      {{ user.first_name }}
                  {% endif %}
                    <a class="settings"
                       href="{% url 'users:profile' pk=user.id %}"> &nbsp &nbsp &nbsp ویرایش پروفایل </a></span>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="col s4 ltr">
                    <div class="card left">

                        <a class="waves-effect waves-light btn btntest" href="{% url 'advertises:create' %}"> ایجاد تست
                            + </a>
                    </div>


                </div>
            </div>
        </div>

        {% if object_list %}
            <div class="tests">
                {% for test in  object_list %}
                    <div class="card cardTest">
                        {% if test.invoice.payment == 1 %}

                            <a href="{% url 'advertises:statistic' pk=test.pk %}">
                        {% else %}
                            <a href="{% url 'advertises:update' pk=test.pk %}">

                        {% endif %}
                        <div class="card-image waves-effect waves-block waves-light">
                            {% if test.is_finished == 1 %}
                                <p class="status2 font"> تمام شده </p>
                            {% else %}
                                <p class="status font"> در حال انجام </p>
                            {% endif %}
                            {% if test.first_pic %}
                                <img class="activator" src="{% get_media_prefix %}{{ test.first_pic }}">
                            {% else %}
                                <img class="activator" src="{% static 'assets/a.jpg' %}">
                            {% endif %}
                        </div>

                        </a>


                        <div class="card-content row">
                            <div class="col s12 rtla">
                                <span class="black-text testti">
                                    {{ test.title }}
                                </span>
                            </div>
                            <div class="col s3">
                                {% if not test.user.profile_picture %}
                                    <img src="{% static 'assets/b.jpg' %}" alt="" class="circle responsive-img">
                                {% else %}
                                    <img src="{% get_media_prefix %}{{ test.user.profile_picture }}" alt=""
                                         class="circle responsive-img">
                                {% endif %}
                                <!-- notice the "circle" class -->
                            </div>
                            <div class="col s9 rtl userna">
                                <a href="{% url 'advertises:update' pk=test.pk %}">
                              <span class="black-text usern">
                                  {{ test.user.first_name }}
                              </span>
                                </a>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            </div>

        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col s12">
                        <div class=" center">
                            <img class="empty" src="{% static 'assets/notest.png' %}" alt="">
                        </div>
                        <div class="center fonta">
                            <p class="center"> در حال حاضر تست برای انجام نیست </p>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </main>

{% endblock %}